language: cpp
dist: xenial
matrix:
  include:
    # Linux GCC
    - name: "Linux GCC-7 Debug"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - TRAVIS_BUILD_TYPE=Debug

    - name: "Linux GCC-7 Release"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - TRAVIS_BUILD_TYPE=Release

    # Linux Clang
    - name: "Linux clang-6.0 Debug"
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - libllvm6.0
            - libclang-common-6.0-dev
            - libclang1-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && CMAKE_CXX_FLAGS=-std=c++17"
        - TRAVIS_BUILD_TYPE=Debug

    - name: "Linux clang-6.0 Release"
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - libllvm6.0
            - libclang-common-6.0-dev
            - libclang1-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && CMAKE_CXX_FLAGS=-std=c++17"
        - TRAVIS_BUILD_TYPE=Release

    - name: "Linux clang-7.0 Debug"
      os: linux
      dist: xenial
      # addons:
      #   apt:
      #     # sources:
      #     #   - llvm-toolchain-xenial-7.0
      #     packages:
      #       - clang-7
      #       # - libc++-dev
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"
        - TRAVIS_BUILD_TYPE=Debug

    - name: "Linux clang-7.0 Release"
      os: linux
      dist: xenial
      # addons:
      #   apt:
      #     # sources:
      #     #   - llvm-toolchain-xenial-7.0
      #     packages:
      #       - clang-7
      #       # - libc++-dev
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"
        - TRAVIS_BUILD_TYPE=Release

    # OSX Clang
    - name: "OS X Xcode 10 Debug"
      os: osx
      osx_image: xcode10.1
      env:
        - TRAVIS_BUILD_TYPE=Debug
    
    - name: "OS X Xcode 10 Release"
      os: osx
      osx_image: xcode10.1
      env:
        - TRAVIS_BUILD_TYPE=Release
    
before_install:
    - eval "${MATRIX_EVAL}"
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DPSST_MATH_BUILD_TESTS=ON -DPSST_MATH_BUILD_BENCHMARKS=OFF -DPSST_MATH_BUILD_EXAMPLES=ON
script:
  - make && make test
  - if [ $? != 0 ]; then test -e Testing/Temporary/LastTest.log && cat Testing/Temporary/LastTest.log || true; fi
 